name: clue_device_id
description: Flutter plugin for get device id with Android and IOS, Supports Android, IOS, Android uses flutter_device_id and iOS uses platform_device_id
version: 0.0.3
repository: https://github.com/suprema-swkim/clue_device_id.git
homepage: https://www.supremainc.com/ko/

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_device_id
      ios:
        default_package: platform_device_id

dependencies:
  flutter:
    sdk: flutter
  flutter_device_id: ^1.0.1
  platform_device_id: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
