name: clue_device_id
description: "A package that manages device IDs used on Android and iOS."
version: 0.0.1
homepage: https://www.supremainc.com/ko/platform/suprema-clue-cloud-managed-service.asp

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_device_id
      ios:
        default_package: platform_device_id

dependencies:
  flutter:
    sdk: flutter
  flutter_device_id: ^1.0.1
  platform_device_id: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
